name: Deploy to EC2 (no Docker)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy via SSH
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Dependencies
        run: |
          npm install -g pnpm
          pnpm install

      - name: Build the app
        run: pnpm build

      - name: Deploy to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: ".next,package.json,ecosystem.config.js,public"
          target: "/home/ubuntu/next-app"

      - name: SSH and restart app with PM2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd next-app
            npm install -g pnpm
            pnpm install --prod
            pm2 start npm --name "next-app" -- start || pm2 restart "next-app"
